In [2]:
# https://www.youtube.com/watch?v=gJo0uNL-5Qw

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [5]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

0.9481481481481482

In [6]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4962962962962963

In [10]:
rfc = RandomForestClassifier(n_estimators=40)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.9722222222222222

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [33]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [34]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [35]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [36]:
scores_rf

[0.9348914858096828, 0.9382303839732888, 0.9131886477462438]

In [37]:
from sklearn.model_selection import cross_val_score

In [39]:
# this is a short cut for the code above
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [40]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92358804, 0.94824708, 0.92114094])